services:
    snidust:
        build: .
        container_name: sniDust
        environment:
            - 'ALLOWED_CLIENTS_FILE=/tmp/myacls.acl'
#            - 'ALLOWED_CLIENTS=0.0.0.0/0, appino.app' # CHANGE THIS
            - 'DNSDIST_ENABLE_WEBSERVER=true'
            - 'DNSDIST_WEBSERVER_NETWORKS_ACL=appinoapphome.ddns.net' # CHANGE THIS
        ports:
            - '443:8443'
            - '80:8080'
            - '81:8083'
            - '63:5300/udp'
            - '63:5300/tcp'
        volumes:
            - './myacls.acl:/tmp/myacls.acl:ro'
        restart: unless-stopped
