server:
  interface: 127.0.0.1
  port: 5335
  do-ip4: yes
  do-ip6: no
  do-udp: yes
  do-tcp: yes
  access-control: 127.0.0.1/32 allow
  prefetch: yes
  num-threads: 1
  msg-cache-size: 25m
  rrset-cache-size: 50m
  so-reuseport: yes
  so-rcvbuf: 8m
  outgoing-range: 8192
  num-queries-per-thread: 4096
  minimal-responses: yes
  rrset-roundrobin: yes
  qname-minimisation: yes
  log-queries: no
  log-replies: no
  verbosity: 1
